# Generated by Django 3.0.13 on 2021-03-07 10:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=57)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('photo', models.ImageField(upload_to='static/image')),
            ],
            options={
                'verbose_name': 'Житель',
                'verbose_name_plural': 'Жители',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
